// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetakesAllocatorCore.Db;

#nullable disable

namespace RetakesAllocatorCore.Migrations
{
    [DbContext(typeof(Db.Db))]
    [Migration("20260205130000_FlatWeaponPreferences")]
    partial class FlatWeaponPreferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("RetakesAllocatorCore.Db.UserSetting", b =>
                {
                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int?>("CT_FullBuyPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CT_HalfBuyPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CT_PistolRound")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CT_Preferred")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CT_Secondary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnemyStuffTeamPreference")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("T_FullBuyPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("T_HalfBuyPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("T_PistolRound")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("T_Preferred")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("T_Secondary")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ZeusEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("UserSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
